#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pubs")]
	public partial class pubsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public pubsDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.pubsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pubsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchForAuthor")]
		public ISingleResult<SearchForAuthorResult> SearchForAuthor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string ssn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ssn);
			return ((ISingleResult<SearchForAuthorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SalesByAuthor")]
		public ISingleResult<SalesByAuthorResult> SalesByAuthor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string au_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), au_id);
			return ((ISingleResult<SalesByAuthorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAuthorID", IsComposable=true)]
		public string GetAuthorID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string login_name)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login_name).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoginAuthor", IsComposable=true)]
		public System.Nullable<bool> LoginAuthor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string password)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListAuthors")]
		public ISingleResult<ListAuthorsResult> ListAuthors()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListAuthorsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAuthor")]
		public ISingleResult<GetAuthorResult> GetAuthor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string au_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), au_id);
			return ((ISingleResult<GetAuthorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListDrafts")]
		public ISingleResult<ListDraftsResult> ListDrafts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string au_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), au_id);
			return ((ISingleResult<ListDraftsResult>)(result.ReturnValue));
		}
	}
	
	public partial class SearchForAuthorResult
	{
		
		private string _au_fname;
		
		private string _au_lname;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _phone;
		
		private string _bat_phone;
		
		private string _ssn;
		
		public SearchForAuthorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_au_fname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string au_fname
		{
			get
			{
				return this._au_fname;
			}
			set
			{
				if ((this._au_fname != value))
				{
					this._au_fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_au_lname", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string au_lname
		{
			get
			{
				return this._au_lname;
			}
			set
			{
				if ((this._au_lname != value))
				{
					this._au_lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(40)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Char(2)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="Char(5)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this._zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bat_phone", DbType="VarChar(20)")]
		public string bat_phone
		{
			get
			{
				return this._bat_phone;
			}
			set
			{
				if ((this._bat_phone != value))
				{
					this._bat_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ssn", DbType="VarChar(12)")]
		public string ssn
		{
			get
			{
				return this._ssn;
			}
			set
			{
				if ((this._ssn != value))
				{
					this._ssn = value;
				}
			}
		}
	}
	
	public partial class SalesByAuthorResult
	{
		
		private string _title;
		
		private System.Nullable<int> _sold;
		
		public SalesByAuthorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sold", DbType="Int")]
		public System.Nullable<int> sold
		{
			get
			{
				return this._sold;
			}
			set
			{
				if ((this._sold != value))
				{
					this._sold = value;
				}
			}
		}
	}
	
	public partial class ListAuthorsResult
	{
		
		private string _au_fname;
		
		private string _au_lname;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _phone;
		
		private string _bat_phone;
		
		private string _ssn;
		
		private System.Nullable<decimal> _commission;
		
		public ListAuthorsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_au_fname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string au_fname
		{
			get
			{
				return this._au_fname;
			}
			set
			{
				if ((this._au_fname != value))
				{
					this._au_fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_au_lname", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string au_lname
		{
			get
			{
				return this._au_lname;
			}
			set
			{
				if ((this._au_lname != value))
				{
					this._au_lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(40)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Char(2)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="Char(5)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this._zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bat_phone", DbType="VarChar(30)")]
		public string bat_phone
		{
			get
			{
				return this._bat_phone;
			}
			set
			{
				if ((this._bat_phone != value))
				{
					this._bat_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ssn", DbType="VarChar(30)")]
		public string ssn
		{
			get
			{
				return this._ssn;
			}
			set
			{
				if ((this._ssn != value))
				{
					this._ssn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commission", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> commission
		{
			get
			{
				return this._commission;
			}
			set
			{
				if ((this._commission != value))
				{
					this._commission = value;
				}
			}
		}
	}
	
	public partial class GetAuthorResult
	{
		
		private string _au_id;
		
		private string _au_fname;
		
		private string _au_lname;
		
		private string _bat_phone;
		
		private string _ssn;
		
		public GetAuthorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_au_id", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string au_id
		{
			get
			{
				return this._au_id;
			}
			set
			{
				if ((this._au_id != value))
				{
					this._au_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_au_fname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string au_fname
		{
			get
			{
				return this._au_fname;
			}
			set
			{
				if ((this._au_fname != value))
				{
					this._au_fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_au_lname", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string au_lname
		{
			get
			{
				return this._au_lname;
			}
			set
			{
				if ((this._au_lname != value))
				{
					this._au_lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bat_phone", DbType="VarChar(30)")]
		public string bat_phone
		{
			get
			{
				return this._bat_phone;
			}
			set
			{
				if ((this._bat_phone != value))
				{
					this._bat_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ssn", DbType="VarChar(30)")]
		public string ssn
		{
			get
			{
				return this._ssn;
			}
			set
			{
				if ((this._ssn != value))
				{
					this._ssn = value;
				}
			}
		}
	}
	
	public partial class ListDraftsResult
	{
		
		private int _draft_id;
		
		private string _title;
		
		public ListDraftsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_draft_id", DbType="Int NOT NULL")]
		public int draft_id
		{
			get
			{
				return this._draft_id;
			}
			set
			{
				if ((this._draft_id != value))
				{
					this._draft_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
